name: To test the code coverage

on:
 workflow_dispatch:

jobs:
  check_out_code:
   runs-on: ubuntu-latest
   steps:
    
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: setting up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: execuing python code
      run: python myapp.py
       
    
